CREATE TABLE IF NOT EXISTS `roles` (
  `Role` VARCHAR(20) NULL DEFAULT NULL,
  `roleID` INT(11) NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`roleID`),
  UNIQUE INDEX `Role` (`Role` ASC))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8